2021-12-14 21:46:51,219 INFO    MainThread:73 [wandb_setup.py:_flush():71] setting env: {}
2021-12-14 21:46:51,220 INFO    MainThread:73 [wandb_setup.py:_flush():71] setting login settings: {}
2021-12-14 21:46:51,220 INFO    MainThread:73 [wandb_setup.py:_flush():71] setting login settings: {'api_key': '***REDACTED***'}
2021-12-14 21:46:51,220 INFO    MainThread:73 [wandb_setup.py:_flush():71] setting login settings: {'api_key': '***REDACTED***'}
2021-12-14 21:46:51,220 INFO    MainThread:73 [wandb_setup.py:_flush():71] setting login settings: {}
2021-12-14 21:46:51,221 INFO    MainThread:73 [wandb_init.py:_log_setup():371] Logging user logs to /content/gdrive/MyDrive/colabs/src/wandb/run-20211214_214651-2wkqmo3t/logs/debug.log
2021-12-14 21:46:51,221 INFO    MainThread:73 [wandb_init.py:_log_setup():372] Logging internal logs to /content/gdrive/MyDrive/colabs/src/wandb/run-20211214_214651-2wkqmo3t/logs/debug-internal.log
2021-12-14 21:46:51,222 INFO    MainThread:73 [wandb_init.py:_jupyter_setup():321] configuring jupyter hooks <wandb.sdk.wandb_init._WandbInit object at 0x7fd51a30ee90>
2021-12-14 21:46:51,222 INFO    MainThread:73 [wandb_init.py:init():404] calling init triggers
2021-12-14 21:46:51,223 INFO    MainThread:73 [wandb_init.py:init():411] wandb.init called with sweep_config: {}
config: {'learning_rate': 0.001, 'epochs': 1000, 'batch_size': 32, 'loss_function': 'CTC', 'architecture': 'Bluche', 'dataset': 'KHATT'}
2021-12-14 21:46:51,223 INFO    MainThread:73 [wandb_init.py:init():449] starting backend
2021-12-14 21:46:51,223 INFO    MainThread:73 [backend.py:_multiprocessing_setup():97] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2021-12-14 21:46:51,245 INFO    MainThread:73 [backend.py:ensure_launched():199] starting backend process...
2021-12-14 21:46:51,262 INFO    MainThread:73 [backend.py:ensure_launched():205] started backend process with pid: 384
2021-12-14 21:46:51,271 INFO    MainThread:73 [wandb_init.py:init():458] backend started and connected
2021-12-14 21:46:51,330 INFO    MainThread:73 [wandb_run.py:_label_probe_notebook():917] probe notebook
2021-12-14 21:46:56,351 INFO    MainThread:73 [wandb_run.py:_label_probe_notebook():927] Unable to probe notebook: 'NoneType' object has no attribute 'get'
2021-12-14 21:46:56,352 INFO    MainThread:73 [wandb_init.py:init():519] updated telemetry
2021-12-14 21:46:56,363 INFO    MainThread:73 [wandb_init.py:init():549] communicating current version
2021-12-14 21:46:56,420 INFO    MainThread:73 [wandb_init.py:init():554] got version response 
2021-12-14 21:46:56,420 INFO    MainThread:73 [wandb_init.py:init():564] communicating run to backend with 30 second timeout
2021-12-14 21:46:56,569 INFO    MainThread:73 [wandb_init.py:init():592] starting run threads in backend
2021-12-14 21:46:58,970 INFO    MainThread:73 [wandb_run.py:_console_start():1816] atexit reg
2021-12-14 21:46:58,977 INFO    MainThread:73 [wandb_run.py:_redirect():1690] redirect: SettingsConsole.WRAP
2021-12-14 21:46:58,978 INFO    MainThread:73 [wandb_run.py:_redirect():1727] Wrapping output streams.
2021-12-14 21:46:58,986 INFO    MainThread:73 [wandb_run.py:_redirect():1751] Redirects installed.
2021-12-14 21:46:58,986 INFO    MainThread:73 [wandb_init.py:init():619] run started, returning control to user process
2021-12-14 21:46:58,987 INFO    MainThread:73 [wandb_init.py:_pause_backend():284] pausing backend
2021-12-14 21:46:58,987 INFO    MainThread:73 [jupyter.py:save_ipynb():374] not saving jupyter notebook
2021-12-14 21:47:24,150 INFO    MainThread:73 [wandb_init.py:_resume_backend():293] resuming backend
